_wandb:
    value:
        cli_version: 0.22.2
        code_path: code/train.py
        e:
            3qf0inrxhg5ns59phfzn0sp6ut6whtpq:
                args:
                    - --weights
                    - --cuda
                    - --mb
                    - "16000"
                    - --lr
                    - ".01"
                    - --torus
                    - --wandb
                    - --wandb_name
                    - Rn
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "108663746330624"
                        used: "106367623778304"
                email: clairefz@mit.edu
                executable: /home/claire/torus/.venv/bin/python
                git:
                    commit: 856178cd8f915fef7aa7c0d4488e12bfebef9a73
                    remote: git@github.com:czhang2718/pytorch-sgns-torus.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-9884c450-fc19-a8df-2d53-c2a5ed3686dc
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-0c8b845a-45f9-b65a-43c8-3aafea7073ae
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-790d194b-fc72-e145-d673-2032c598a402
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-bfc29916-bb71-fb4a-c5c5-e8433462415b
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-f28fe93c-78b7-e597-cf68-351c8596b48d
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-c9d3dedf-ca71-a3b3-8b6e-9410eab05d44
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-fae0a58a-de5a-4004-54f4-a958bbb4ef73
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-2ebd5d6d-002c-fcbb-3073-898e6e3a2897
                host: worker-4
                memory:
                    total: "1690974609408"
                os: Linux-6.11.0-1013-nvidia-x86_64-with-glibc2.39
                program: /home/claire/pytorch-sgns/train.py
                python: CPython 3.13.5
                root: /home/claire/pytorch-sgns
                startedAt: "2025-11-10T00:28:54.487168Z"
                writerId: 3qf0inrxhg5ns59phfzn0sp6ut6whtpq
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.13.5
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 16000
cuda:
    value: true
embedding_dim:
    value: 300
epochs:
    value: 100
learning_rate:
    value: 0.01
n_negs:
    value: 20
subsample_threshold:
    value: 1e-05
torus:
    value: true
use_weights:
    value: true
vocab_size:
    value: 20000
